### ISSUE TITLE
feature/460-create-power-station-class

### ISSUE THREAD

**Issue by wwUbuntu** [swarm-robotics/fordyca#460] opened 2018-11-01 19:15 UTC
The Power-Station will be both an immovable cell entity and a multi cell entity. The following are known attributes of a Power-Station at the time of this issue's creation:

- ID, which will allow the Power-Stations to be identifiable.
- Size, which will determine how large the Power-Station will be
    i. Currently vague; must be refined
    ii. naming of size should also change to be more descriptive

**Comment by jharwell** [comment] 2019-05-15 19:48
Duplicate of #184.

**Closed by jharwell** 2019-05-15 19:48 UTC
Labels: Type: Feature
