### ISSUE TITLE
How to create a static cache

### ISSUE THREAD

**Issue by fangxing123** [swarm-robotics/fordyca#462] opened 2018-11-05 08:55 UTC
Excuse me，did i set a wrong  parameters?
<static_caches enable="true"
                     size="2"
                     respawn_scale_factor="5"
                     dimension="0.8"
                     min_dist="0.8

**Comment by jharwell** [comment] 2018-11-05 15:14
Are you running the latest devel branch? If not, could you post the sha1 of the version of the devel branch that you are running? The format for using static caches has changed a fair bit over that last month or so. Also, you have to be using the depth1 loop functions (qt user functions too) in order for static cache parameters to even be parsed, iirc.

**Comment by fangxing123** [comment] 2018-11-06 09:16
After i update，some error has happend when make 
/home/robot/1/rcppsw/src/task_allocation/src/exec_estimates_parser.cpp:34:44: error: ‘constexpr’ needed for in-class initialization of static data member ‘const char rcppsw::task_allocation::exec_estimates_parser::kXMLRoot [20]’ of non-integral type [-fpermissive]
 const char exec_estimates_parser::kXMLRoot[];
                                            ^
src/task_allocation/CMakeFiles/rcppsw-task_allocation.dir/build.make:446: recipe for target 'src/task_allocation/CMakeFiles/rcppsw-task_allocation.dir/src/exec_estimates_parser.cpp.o' failed
make[2]: *** [src/task_allocation/CMakeFiles/rcppsw-task_allocation.dir/src/exec_estimates_parser.cpp.o] Error 1
CMakeFiles/Makefile2:2019: recipe for target 'src/task_allocation/CMakeFiles/rcppsw-task_allocation.dir/all' failed
make[1]: *** [src/task_allocation/CMakeFiles/rcppsw-task_allocation.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by jharwell** [comment] 2018-11-06 17:11
You are probably using g++ 5.4 or so, which requires constexpr in both the declaration and definition of static class constants. The problem does not occur with g++7. I've updated the devel branch in rcppsw to fix this issue with g++ 5.4 as well.

**Comment by fangxing123** [comment] 2018-11-07 07:36
<loop_functions library="libfordyca"
                  label="depth2_loop_functions">
I have trid stateful/stateless/depth1/depth2,but it always goes wrong：
[FATAL] Error initializing loop functions
[FATAL] Symbol "stateless_foraging_loop_functions" not found
I can not run single-source.argos either.

**Comment by jharwell** [comment] 2018-11-07 16:49
Try `stateless_loop_functions` instead. The name of the exported symbols in libfordyca changed in the current devel branch. I will update the README and the parameter documentation to reflect recent changes (both are embarrassingly out of date).

**Comment by fangxing123** [comment] 2018-11-08 01:02
[INFO] Loaded library "/home/robot/fordyca/build/lib/libfordyca.so"
[INFO] Loaded library "/home/robot/fordyca/build/lib/libfordyca.so"
[FATAL] Error initializing loop functions
[FATAL] Symbol "stateless_loop_functions" not found
It still can't run.

**Comment by jharwell** [comment] 2018-11-08 15:35
Have you re-run cmake since doing a git pull ? There were a lot of new files that will not be compilied otherwise, and can lead to the error you're seeing. Also, if you are using the version of ARGoS from the `.deb`, then you *must* also use g++ 5.4, or you will see the above error. If you have built ARGoS from source, then you can use whatever C++14 compatible compiler you like.

**Comment by fangxing123** [comment] 2018-11-12 09:12
/home/robot/fordyca/ext/rcppsw/include/rcppsw/task_allocation/polled_task.hpp:74:8: note:   candidate expects 2 arguments, 1 provided
/home/robot/fordyca/src/controller/depth1/tasking_initializer.cpp:147:74: error: no matching function for call to ‘rcppsw::task_allocation::polled_task::exec_estimate_init(rcppsw::math::rangeui&)’
After i re-run cmake since doing a git pull,this error comes.

**Comment by jharwell** [comment] 2018-11-12 15:14
That's a result of some refactoring I'm working on right now--should be fixed in the next day or so.

**Comment by jharwell** [comment] 2018-11-15 16:20
Should be good to go now, for the Depth 1 controllers at least :-). Let me know if you find otherwise.

**Comment by fangxing123** [comment] 2018-11-17 09:36
It works.I can run the .argos now.Thanks a lot.
But the simulation is not smooth, it will be stuck every few seconds.And robots behave very strangely，most of them are wandering around.Did I miss some parameters?

**Comment by jharwell** [comment] 2018-11-17 17:00
So you may be running the in-progress depth2 foraging stuff I'm working on, which runs a non-linear optimization algorithm regularly, which may be causing the slowdown you see, although even on stateful foraging I still see some of the choppiness you mention, which is caused by running debug builds with optimizations off. I added a new input file `demo.argos` in #480 which I will keep separate from my in-progress changes in the future, so try that one out and see if it behaves any better. You could also try recompiling with optimizations on, which should help as well, by doing :

`cmake -DCMAKE_BUILD_TYPE=OPT ..`

from your build directory.

**Comment by jharwell** [comment] 2018-11-30 19:24
Marking as solved. Please re-open if it is not or open a new issue if you encounter addtional problems.

**Closed by jharwell** 2018-11-30 19:24 UTC
